from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / "files"
WINDOW_ICON_PATH = FILES_DIR / "ïcon.png"

PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'

BIG_FONT_SIZE = 40
MED_FONT_SIZE = 20
SML_FONT_SIZE = 15
TEXT_MARGIN = 15
MINIMUN_WIDTH = 500
BUTTON_SIZE = 60
